---
name: ci 
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/main.yml
      - mkdocs.yml
      - 'docs/**'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material 
      - run: sudo apt-get install -y pngquant
      - run: pip install mkdocs-git-revision-date-localized-plugin
      - run: pip install pillow cairosvg
      - run: pip install material-plausible-plugin
      - run: pip install mkdocs-awesome-pages-plugin
      - run: pip install mkdocs-redirects
      - run: mkdocs gh-deploy --force
